// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// hai bang
// hai
//hai bang
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBkeF6UNrJ9ukmqZZtvUC8olZ8fQihbeo',
    appId: '1:324099954906:web:2819ff25af5ce6ce3c6de3',
    messagingSenderId: '324099954906',
    projectId: 'smartacaveralpha',
    authDomain: 'smartacaveralpha.firebaseapp.com',
    databaseURL: 'https://smartacaveralpha-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartacaveralpha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1oLpYPAdStw8mRlbAWCRfM4ICbxhM18Y',
    appId: '1:324099954906:android:98477080699b2a603c6de3',
    messagingSenderId: '324099954906',
    projectId: 'smartacaveralpha',
    databaseURL: 'https://smartacaveralpha-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartacaveralpha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW1v34BG2cyIf_aL51SUzYsB4iOvkcW6s',
    appId: '1:324099954906:ios:37213c0d08bdeefd3c6de3',
    messagingSenderId: '324099954906',
    projectId: 'smartacaveralpha',
    databaseURL: 'https://smartacaveralpha-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartacaveralpha.appspot.com',
    iosBundleId: 'com.grounded.smartacaAlpha6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW1v34BG2cyIf_aL51SUzYsB4iOvkcW6s',
    appId: '1:324099954906:ios:2f97826c4318c0433c6de3',
    messagingSenderId: '324099954906',
    projectId: 'smartacaveralpha',
    databaseURL: 'https://smartacaveralpha-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartacaveralpha.appspot.com',
    iosBundleId: 'com.grounded.smartacaAlpha6.RunnerTests',
  );
}
